// Hardcoded Acts & Rules reference data, transcribed from the live Sagarmanthan portal
// (ntcpwcit.in/sagarmanthan -> Legal -> Acts & Rules). Per team decision, this module
// does not hit the backend -- it's a static reference table, matching the live site 1:1.

export const WINGS = ['IWT', 'Ports', 'Shipping Wing', 'PHRD', 'DGLL', 'Sagarmala'];

export const ACTS_AND_RULES = [
  {
    sno: 1,
    wing: 'IWT',
    entries: [
      {
        act: 'The IWAI Act, 1985',
        rules: ['Inland Vessels (Survey and Certification) Rules, 2022'],
      },
      {
        act: 'The National Waterways Act, 2016',
        rules: ['Inland Vessels (Registration and other Technical Issues) Rules, 2022'],
      },
      {
        act: 'Inland Vessels Act, 2021',
        rules: [
          'Inland Vessels (Manning) Rules, 2022',
          'Inland Vessels (Crew and Passenger Accommodation) Rules, 2022',
          'Inland Vessels (Safe Navigation, Communication and Signals) Rules, 2022',
          'Inland Vessels (Life Saving Appliances) Rules, 2022',
          'Inland Vessels (Fire Fighting Appliances) Rules, 2022',
          'Inland Vessels (Prevention and Containment of Pollution) Rules, 2022',
          'Inland Vessels (Insurance & Liability) Rules, 2022',
          'The IWAI Rules, 1986',
          'Inland Vessels (Design and Construction) Rules, 2023',
        ],
      },
    ],
  },
  {
    sno: 2,
    wing: 'Ports',
    entries: [
      {
        act: 'The Major Port Authorities Act, 2021',
        rules: [
          'The Major Port Adjudicatory Board Rules, 2023',
          'The Major Port Authorities (Audit and Accounts) Rule 2021.',
          'The Major Port Authorities (Chairperson, Deputy Chairperson and Board Members) Rules, 2022',
          'The Major Port Authorities (Master Plan and Application of Funds from Non Port related Use) Rules, 2022',
          'The Major Port Authorities (Application of Money in Sinking Fund) Rules, 2021',
          'The Major Port Authorities (Fixation and Implementation of Scale of Rates, Fees and Conditions) Rules, 2021',
          'The Major Port Authorities (Corporate Social Responsibility) Rules, 2021',
        ],
      },
    ],
  },
  {
    sno: 3,
    wing: 'Shipping Wing',
    entries: [
      {
        act: 'The Merchant Shipping Act, 1958',
        rules: [
          'The Merchant Shipping (Maritime Labour) Rules, 2016 (alongwith the 2016 amendments)',
          'The Merchant Shipping (Control of Anti-fouling System) Rules, 2016',
          'The Merchant Shipping (Limitation of Liability for Maritime Claims) Rules, 2015 (alongwith the 2017 amendments to the said Rules)',
          'The Merchant Shipping (Apprenticeship To Sea-Service) Rules, 1960',
          'The Merchant Shipping (Cancellation or Suspension of Certificate of Competency) Rules, 2003',
          'The Merchant Shipping Cargo ship Construction & Survey Rules, 1991',
          'The Merchant Shipping (Carriage of Cargo) Rules, 1995',
          'The Merchant Shipping (Condition for carriage of Livestocks) Rules,2020',
          'The Merchant Shipping (Carriage Of Medical Officer) Rule, 1961',
          'The Merchant Shipping (Certificates of Competency) Rules, 1989',
          'The Merchant Shipping (Certificate of Service) Rules, 1970',
          "The Merchant Shipping (Construction and Survey of Passenger Ships Rules, 1981",
          'Merchant Shipping (Continues Discharge Certificate) Rules, 2017',
          'Merchant Shipping (Seafarers Bio-metric Identity Document) Rules, 2016',
          'Merchant Shipping (Crew Accommodation) Rules, 1960 (along with amendments of 1967, 1970, 1984, 1993, 1999)',
          'Merchant Shipping (Seafarer Accommodation) Rules, 2016',
          'Merchant Shipping (Distressed and Safety Radio Communication) Rules, 1995',
          'Merchant Shipping (Examination of Dredge Driver and Dredge Engineers) Rules, 1982',
          'Merchant Shipping Examination of Dredged Masters & Dredged Mates, Rule 1985',
          'Merchant Shipping (Examination of Engineers & Engine Drivers of Fishing Vessels), Rules 1973 (along with amendments of 1975, 1976 and 1991)',
          'Merchant Shipping (Examination of Engine Drivers of sea going ships), Rules 1973 (along with amendments of 1991 and 1992)',
          'Merchant Shipping (Examination Of Engineer Officers in the Merchant Navy) Rules, 1989 (alongwith the amendments of 1994)',
          'Merchant Shipping (Examination of Masters and Mates) Rules, 1985 (along with the amendments of 1990)',
          'The Merchant Shipping (Examination of Skippers and Mate of Fishing Vessels) Rules, 1987',
          'Merchant Shipping (Fees For Load Lines Surveys) Rules, 1979',
          'Merchant Shipping (Fire Appliances) Rule, 1990 (along with the amendment of 1994)',
          'The Merchant Shipping (Form of Certificate of Insurance for Civil Liability for Oil Pollution Damage) Rules, 1985 (along with the amendments of 1990)',
          'The Merchant Shipping (Form of Particulars of Certificates and Employment) Rules, 1980',
          "The Merchant Shipping (Form of Passenger Ships' Survey Certificates) Rules, 1992",
          'The Merchant Shipping (Forms of Licences) Rules, 1960',
          'The Merchant Shipping (Shipping Office Forms) Rules, 1963 (along with the amendments of 1976)',
          'The Merchant Shipping (Levy of Oil Pollution Cess) Rules 1988',
          'The Merchant Shipping (Life Saving Appliances) Rules 1991 (along with the amendments of 1995)',
          'Lifeboatmans (Qualifications & Certificates) Rules,1963 (along with the amendments of 1970, 1973, 1974)',
          'Merchant Shipping (Load Line) Rules, 1979 (along with the amendments of 1982, 1989 and 2001)',
          'Merchant Shipping (Management for the Safe Operation of Ships) Rules, 2000 (along with amendments of 2002, 2003 and 2014)',
          'Merchant Shipping (Medical Examination) Rules, 2000 (along with the 2016 amendment to the said rules)',
          'Merchant Shipping (Medical Examination) TT Rules, 1986',
          'Merchant Shipping (Medicines, Medical Stores and Appliances) Rules, 1994',
          'The National Shipping Board Rules, 1960 (along with the 1991 amendment to the said rules)',
          'The National Welfare Board for Seafarers Rules, 1963',
          'Merchant Shipping (Payment of expenses to Witness) Rules, 1986',
          'Indian Pilgrim Ship Rules, 1933',
          'Merchant Shipping (Pilot Ladder) Rule, 1967',
          'Merchant Shipping (Prevention of Collisions at Sea) Rule, 1975 (along with the 1986 and 1990 amendment to the Regulations)',
          'Merchant Shipping (Radio Direction Finders) Rules, 1968',
          'Merchant Shipping (Radio) Rules, 1983 (along with the 1992 amendment to the Rules)',
          'Merchant Shipping (Rates)Rules, 1977',
          'Merchant Shipping (Recruitment and Placement of Seafarers) Rules, 2016 (along with the 2022 amendment to the rules)',
          'The Merchant Shipping (Registration of Indian Fishing Boats), Rules, 1988',
          'Merchant Shipping (Indian Fishing Boats Inspection) Rules, 1988',
          'Merchant Shipping (Conditions for Carriage of Livestock) Rules, 2020',
          'Merchant Shipping (Sailing Vessels) Rules, 1997',
          'Merchant Shipping (Registration of Indian Ships) Rules, 1960 (along with the 1994 and 1997 amendment to the Rules)',
          'Merchant Shipping Seamens Employment Offices Rules,1986',
          'Merchant Shipping (Levy of Seamen\u2019s Welfare Fee) Rules, 1974 (along with the 1982, 2015 and 2017 amendments) to the said Rules',
          'The Seamen (Supply of Articles for Personal use) Rules, 1966 (along with 1976, 1978 and 1988 amendments to the said Rules)',
          'Merchant Shipping (Safety Convention Certificates) Rules, 1968 (along with the 1978, 1988 and 1995 amendments to the said Rules)',
          'Merchant Shipping (Safety of Navigation) Rules, 1997',
          'Merchant Shipping (Standards of Training, Certification & Watch keeping for Seafarers) Rules, 2014 (along with 2019 amendment to the said Rules)',
          'Merchant Shipping (Tonnage Measurement of Ships) Rules, 1987(along with 1991, 1992 and 1995 amendments to the said Rules)',
          'Merchant Shipping (Wrecks and Salvage) Rules, 1974(along with 1975 amendment to the said Rules)',
          'The Merchant Shipping (control of Pollution by Noxious Liquid Substance in Bulk) Rules, 2010',
          'The Merchant Shipping (Prevention of Pollution by Harmful Substances carried by Sea in Packaged Form) Rules, 2010',
          'The Merchant Shipping (Prevention of Pollution by Sewage from ships) Rules, 2010. (Annex-IV)',
          'The Merchant Shipping (Prevention of Pollution by Garbage from Ships) Rules, 2010. (Annex-V)',
          'Merchant Shipping (Prevention of Pollution by Oil from Ships) Rules, 2010',
          'The Merchant Shipping (Civil Lability for Oil Pollution Damage) Rules, 2008',
          'The Merchant Shipping (International Fund for Compensation for Oil Pollution Damage) Rules, 2008',
          'Merchant Shipping (Regulations of Entry of Ships into Ports, Anchorages and Offshore facilities) Rules, 2012',
        ],
      },
      {
        act: 'The Multimodal Transportation of Goods Act, 1993 (as amended in December, 2000)',
        rules: ['The Registration of Multimodal Transport Operators Rules, 1992 & MTD Rules, 1994'],
      },
      {
        act: 'Admiralty (Jurisdiction & Settlement of Maritime Claims) Act, 2017',
        rules: [],
      },
      {
        act: 'Indian Bills of Lading Act, 1856-No Rules',
        rules: [
          'The Admiralty (Assessors) Rules, 2018',
          'The Calcutta High Court Admiralty (Jurisdiction and settlement of Maritime claims) Rules, 2019',
          'Rules for Regulating the Procedure and Practice in cases brought before the High Court under the Admiralty Jurisdiction And Settlement Of Maritime Claims Act, 2017',
          'The Rules for Regulating the Procedure and Practice in cases brought before the High Court of Judicature at Madras in the exercise of its Admiralty Jurisdiction framed by the High Court',
          'The Orissa High Court Admiralty (Jurisdiction and Settlement of Maritime Claims) Rules, 2020',
        ],
      },
      { act: 'The Seamens Provident Fund Act, 1966-No Rules', rules: [] },
      { act: 'The Indian Carriage of Goods by Sea Act, 1925 [as amended in the year 2000]- No Rules', rules: [] },
      { act: 'Coasting Vessels Act, 1838-No Rules', rules: [] },
      { act: 'The Recycling of Ships Act, 2019', rules: [] },
      { act: 'The Indian Maritime University Act, 2008-No Rules', rules: [] },
      {
        act: 'The Suppression of Unlawful Acts Against Safety of Maritime Navigation and Fixed Platforms on Continental Shelf Act, 2002-No Rules',
        rules: [],
      },
    ],
  },
  {
    sno: 4,
    wing: 'PHRD',
    entries: [
      { act: 'The Dock Workers (Regulation of Employment) (Inapplicability to Major Ports) Act, 1997-Not yet implemented', rules: [] },
      { act: 'The Dock Workers (Regulation of Employment) Act, 1948', rules: [] },
      { act: 'The Hooghly Docking and Engineering Company Limited (Acquisition and Transfer of Undertakings) Act, 1984', rules: [] },
    ],
  },
  {
    sno: 5,
    wing: 'DGLL',
    entries: [
      {
        act: 'Marine Aids to Navigation Act, 2021',
        rules: [
          'Marine Aids to Navigation (Duties of Director General) Rules, 2022',
          'Marine Aids to Navigation (Development of Heritage td) Rules, 2022',
          'Marine Aids Navigation (Accreditation of Training Organisations) Rules, 2022',
          'Marine Aids to Navigation (Central Advisory Committee Procedural) Rules, 2022',
          'Marine Aids to Navigation (Accounting and Financial Powers) Rules, 2022',
          'Marine Aids to Navigation (Training and Certification) Rules, 2025',
          'Marine Aids to Navigation (Vessel Traffic Services) Rules, 2026',
        ],
      },
    ],
  },
  {
    sno: 6,
    wing: 'Sagarmala',
    entries: [
      {
        act: 'The Indian Ports Act 1908',
        ruleGroups: [
          {
            heading: 'Major Port Rules',
            rules: [
              'The Cochin Harbour Crafts Rules, 1947',
              'The Port of Kandla (Handling and Storage of Compresses Gas Cylinders) Rules, 1955',
              'Indian Port Health Rules, 1955',
              'Madras Port (Harbour Craft) Rules, 1980',
              'The Major Ports (Regulation of Entry, Stay, Movement & Exit of Vessels) Rules, 1989',
              'Jawaharlal Nehru Port (Harbour Craft) Rules, 2007',
              'Major Ports (Prevention & Control of Pollution Rules, 1991',
              'Mormugao Port Rules, 1966',
              'New Mangalore Port (Harbour Craft) Rules, 1976',
              'New Mangalore Port Rules, 1976',
              'Paradip Port Rules, 1966',
              'Paradip Port (Harbour Craft) Rules, 1967',
              'Calcutta Port Rules, 1994',
              'Port of Tuticorin Rules, 1977',
              'Port of Tuticorin (Harbour Craft) Rules, 1976',
              'Vishakhapatnam (Harbour Craft) Rule, 1950',
            ],
          },
          {
            heading: 'Non-Major Port Rules',
            rules: [
              'Andaman & Nicobar Island Port Rule, 2004',
              'Rules and Scale of Rates for the Port Services to be Levied at Ports of Andaman & Nicobar Islands, 2019',
            ],
          },
        ],
      },
    ],
  },
];
