/**
 * UI scaffold mock for Ministry Data QC (Gap Analysis).
 * Counts/samples mirror Projects_Gap_Analysis_Report.xlsx - replace with API later.
 */

export const DATA_QC_CHECKS = [
  {
    id: 'tendering-missing',
    group: 'Tendering',
    shortLabel: '1. Tendering-Missing Dates',
    title: '1. Projects under Tendering - Missing Stage Target Dates',
    severity: 'warning',
    count: 60,
    description: 'Target dates not entered for one or more tendering stages.',
    columns: [
      { field: 'slNo', headerName: 'Sl. No.', width: 80 },
      { field: 'organisation', headerName: 'Port/Organisation', minWidth: 180, flex: 1.2 },
      { field: 'projectCode', headerName: 'Project ID/Code', width: 110 },
      { field: 'projectName', headerName: 'Project Name', minWidth: 220, flex: 1.6 },
      { field: 'stage', headerName: 'Project Stage/Status', width: 140 },
      { field: 'milestones', headerName: 'Relevant Stage/Milestone', minWidth: 220, flex: 1.4 },
      { field: 'targetDate', headerName: 'Existing Target Date', width: 140 },
      { field: 'actualDate', headerName: 'Actual Date', width: 120 },
      { field: 'issue', headerName: 'Current Status/Issue', minWidth: 240, flex: 1.6 },
      { field: 'action', headerName: 'Required Action/Update', minWidth: 200, flex: 1.3 },
    ],
    rows: [
      {
        slNo: 1,
        organisation: 'Deendayal Port Authority',
        projectCode: 'PR0055',
        projectName: 'Mechanization Fertilizer and Other Clean Cargo Handling Facilities at Berth No-14',
        stage: 'Under Tendering',
        milestones: 'Technical Evaluation Completed; Financial Evaluation Completed; … (5 stages)',
        targetDate: 'Not Available',
        actualDate: 'Not Available',
        issue: 'Target date not entered for 5 stage(s)',
        action: 'Port/Organisation to enter planned target date for the stage(s) listed',
      },
      {
        slNo: 2,
        organisation: 'Cochin Port Authority',
        projectCode: 'PR0147',
        projectName: 'Implementation of 1.5MWp grid connected floating solar PV power plant under RESCO model',
        stage: 'Under Tendering',
        milestones: 'Sanction of Competent Authority for Award; Work Awarded / LOA Issued; Contract Agreement Signed',
        targetDate: 'Not Available',
        actualDate: 'Not Available',
        issue: 'Target date not entered for 3 stage(s)',
        action: 'Port/Organisation to enter planned target date for the stage(s) listed',
      },
      {
        slNo: 3,
        organisation: 'Jawaharlal Nehru Port Authority',
        projectCode: 'PR0410',
        projectName: 'Development of Greenfield Vadhvan Port.',
        stage: 'Under Tendering',
        milestones: 'Tech Sanction Obtained through Contract Agreement Signed (8 stages)',
        targetDate: 'Not Available',
        actualDate: 'Not Available',
        issue: 'Target date not entered for 8 stage(s)',
        action: 'Port/Organisation to enter planned target date for the stage(s) listed',
      },
    ],
  },
  {
    id: 'tendering-overdue',
    group: 'Tendering',
    shortLabel: '2. Tendering-Overdue Dates',
    title: '2. Projects under Tendering - Overdue Stage Target Dates',
    severity: 'critical',
    count: 37,
    description: 'Stage target dates have expired with no actual completion recorded.',
    columns: [
      { field: 'slNo', headerName: 'Sl. No.', width: 80 },
      { field: 'organisation', headerName: 'Port/Organisation', minWidth: 180, flex: 1.2 },
      { field: 'projectCode', headerName: 'Project ID/Code', width: 110 },
      { field: 'projectName', headerName: 'Project Name', minWidth: 220, flex: 1.6 },
      { field: 'stage', headerName: 'Project Stage/Status', width: 140 },
      { field: 'milestones', headerName: 'Relevant Stage/Milestone', minWidth: 200, flex: 1.3 },
      { field: 'targetDate', headerName: 'Existing Target Date', minWidth: 180, flex: 1.2 },
      { field: 'actualDate', headerName: 'Actual Date', width: 120 },
      { field: 'issue', headerName: 'Current Status/Issue', minWidth: 240, flex: 1.6 },
      { field: 'action', headerName: 'Required Action/Update', minWidth: 200, flex: 1.3 },
    ],
    rows: [
      {
        slNo: 1,
        organisation: 'Cochin Port Authority',
        projectCode: 'PR0146',
        projectName: 'Development of Onshore Power Supply for Cruise vessels at COPT',
        stage: 'Under Tendering',
        milestones: 'Tender Document Approved through Contract Agreement Signed (7 stages)',
        targetDate: '31-03-2026 … 31-08-2026',
        actualDate: 'Not Available',
        issue: 'Target date expired for 7 stage(s) with no actual completion recorded',
        action: 'Update actual completion date, or provide revised target with reasons for delay',
      },
      {
        slNo: 2,
        organisation: 'Cochin Port Authority',
        projectCode: 'PR0147',
        projectName: 'Implementation of 1.5MWp grid connected floating solar PV power plant under RESCO model',
        stage: 'Under Tendering',
        milestones: 'Financial Evaluation Completed',
        targetDate: '31-07-2025',
        actualDate: 'Not Available',
        issue: 'Target date expired - overdue 397 days',
        action: 'Update actual completion date, or provide revised target with reasons for delay',
      },
      {
        slNo: 3,
        organisation: 'V.O. Chidambaranar Port Authority',
        projectCode: 'PR0453',
        projectName: 'Development of Outer Harbour Container Terminal at VOC Port on HAM and DBFOT Basis',
        stage: 'Under Tendering',
        milestones: 'Technical Evaluation Completed through Contract Agreement Signed (5 stages)',
        targetDate: '31-07-2024 … 30-09-2024',
        actualDate: 'Not Available',
        issue: 'Target date expired for 5 stage(s) - overdue 700+ days',
        action: 'Update actual completion date, or provide revised target with reasons for delay',
      },
    ],
  },
  {
    id: 'tendering-foundation',
    group: 'Tendering',
    shortLabel: '3. Tendering-Foundation',
    title: '3. Projects under Tendering - Foundation Not Laid & Foundation-Laying Date Missing',
    severity: 'attention',
    count: 85,
    description: 'Foundation not laid and/or foundation-laying date missing.',
    columns: [
      { field: 'slNo', headerName: 'Sl. No.', width: 80 },
      { field: 'organisation', headerName: 'Port/Organisation', minWidth: 180, flex: 1.2 },
      { field: 'projectCode', headerName: 'Project ID/Code', width: 110 },
      { field: 'projectName', headerName: 'Project Name', minWidth: 220, flex: 1.6 },
      { field: 'stage', headerName: 'Project Stage/Status', width: 140 },
      { field: 'milestones', headerName: 'Relevant Stage/Milestone', width: 160 },
      { field: 'targetDate', headerName: 'Target Date', width: 130 },
      { field: 'issue', headerName: 'Current Status/Issue', minWidth: 220, flex: 1.5 },
      { field: 'action', headerName: 'Required Action/Update', minWidth: 200, flex: 1.3 },
    ],
    rows: [
      {
        slNo: 1,
        organisation: 'Deendayal Port Authority',
        projectCode: 'PR0055',
        projectName: 'Mechanization Fertilizer and Other Clean Cargo Handling Facilities at Berth No-14',
        stage: 'Under Tendering',
        milestones: 'Foundation Laying',
        targetDate: 'Not Available',
        issue: 'Foundation not laid; foundation-laying date missing',
        action: 'Provide expected/tentative foundation-laying date',
      },
      {
        slNo: 2,
        organisation: 'Cochin Port Authority',
        projectCode: 'PR0146',
        projectName: 'Development of Onshore Power Supply for Cruise vessels at COPT',
        stage: 'Under Tendering',
        milestones: 'Foundation Laying',
        targetDate: '30-09-2026',
        issue: 'Foundation not laid; status recorded as No',
        action: 'Confirm/update tentative foundation-laying date is still valid',
      },
    ],
  },
  {
    id: 'implementation-missing',
    group: 'Implementation',
    shortLabel: '4. Implementation-Missing',
    title: '4. Projects under Implementation - Missing Stage/Milestone Target Dates',
    severity: 'warning',
    count: 81,
    description: 'Milestone target end dates not entered for projects under implementation.',
    columns: [
      { field: 'slNo', headerName: 'Sl. No.', width: 80 },
      { field: 'organisation', headerName: 'Port/Organisation', minWidth: 180, flex: 1.2 },
      { field: 'projectCode', headerName: 'Project ID/Code', width: 110 },
      { field: 'projectName', headerName: 'Project Name', minWidth: 220, flex: 1.6 },
      { field: 'stage', headerName: 'Project Stage/Status', width: 160 },
      { field: 'milestones', headerName: 'Relevant Stage/Milestone', minWidth: 200, flex: 1.3 },
      { field: 'issue', headerName: 'Current Status/Issue', minWidth: 220, flex: 1.5 },
      { field: 'action', headerName: 'Required Action/Update', minWidth: 200, flex: 1.3 },
    ],
    rows: [
      {
        slNo: 1,
        organisation: 'Mumbai Port Authority',
        projectCode: 'PR0017',
        projectName: 'Establishment of 600 bedded super specialty hospital on PPP',
        stage: 'Under Implementation',
        milestones: 'Milestone 0 through Milestone 5',
        issue: 'Target end date not entered for 6 milestone(s)',
        action: 'Enter target end date for the milestone(s) listed',
      },
      {
        slNo: 2,
        organisation: 'Deendayal Port Authority',
        projectCode: 'PR0043',
        projectName: 'Development of Container Terminal at Tuna-Tekra on BOT basis under PPP mode',
        stage: 'Under Implementation',
        milestones: 'Milestone 0; Milestone 3; Milestone 4',
        issue: 'Target end date not entered for 3 milestone(s)',
        action: 'Enter target end date for the milestone(s) listed',
      },
    ],
  },
  {
    id: 'implementation-overdue',
    group: 'Implementation',
    shortLabel: '5. Implementation-Overdue',
    title: '5. Projects under Implementation - Overdue Stage/Milestone Target Dates',
    severity: 'critical',
    count: 87,
    description: 'Milestone targets expired with no actual end date recorded.',
    columns: [
      { field: 'slNo', headerName: 'Sl. No.', width: 80 },
      { field: 'organisation', headerName: 'Port/Organisation', minWidth: 180, flex: 1.2 },
      { field: 'projectCode', headerName: 'Project ID/Code', width: 110 },
      { field: 'projectName', headerName: 'Project Name', minWidth: 220, flex: 1.6 },
      { field: 'stage', headerName: 'Project Stage/Status', width: 160 },
      { field: 'milestones', headerName: 'Relevant Stage/Milestone', minWidth: 180, flex: 1.2 },
      { field: 'issue', headerName: 'Current Status/Issue', minWidth: 220, flex: 1.5 },
      { field: 'action', headerName: 'Required Action/Update', minWidth: 200, flex: 1.3 },
    ],
    rows: [
      {
        slNo: 1,
        organisation: 'Sample Port Authority',
        projectCode: 'PR0000',
        projectName: 'Sample implementation overdue project (UI scaffold)',
        stage: 'Under Implementation',
        milestones: 'Milestone 2; Milestone 3',
        issue: 'Target end date expired for 2 milestone(s) with no actual completion',
        action: 'Update actual end date or revise target with reasons for delay',
      },
    ],
  },
  {
    id: 'implementation-inauguration',
    group: 'Implementation',
    shortLabel: '6. Implementation-Inauguration',
    title: '6. Projects under Implementation - Not Yet Inaugurated & Inauguration Date Missing',
    severity: 'attention',
    count: 204,
    description: 'Project not yet inaugurated and/or inauguration date needs confirmation.',
    columns: [
      { field: 'slNo', headerName: 'Sl. No.', width: 80 },
      { field: 'organisation', headerName: 'Port/Organisation', minWidth: 180, flex: 1.2 },
      { field: 'projectCode', headerName: 'Project ID/Code', width: 110 },
      { field: 'projectName', headerName: 'Project Name', minWidth: 220, flex: 1.6 },
      { field: 'stage', headerName: 'Project Stage/Status', width: 160 },
      { field: 'milestones', headerName: 'Relevant Stage/Milestone', width: 140 },
      { field: 'targetDate', headerName: 'Target Date', width: 140 },
      { field: 'issue', headerName: 'Current Status/Issue', minWidth: 220, flex: 1.5 },
      { field: 'action', headerName: 'Required Action/Update', minWidth: 200, flex: 1.3 },
    ],
    rows: [
      {
        slNo: 1,
        organisation: 'Deendayal Port Authority',
        projectCode: 'PR0043',
        projectName: 'Development of Container Terminal at Tuna-Tekra, Deendayal Port',
        stage: 'Under Implementation',
        milestones: 'Inauguration',
        targetDate: '27-02-2027',
        issue: 'Project not yet inaugurated',
        action: 'Confirm/update tentative inauguration date is still valid',
      },
      {
        slNo: 2,
        organisation: 'Deendayal Port Authority',
        projectCode: 'PR0058',
        projectName: 'Development, Operation & Maintenance of Berth-13',
        stage: 'Under Implementation',
        milestones: 'Inauguration',
        targetDate: 'Not Available',
        issue: 'Project not yet inaugurated; inauguration date missing',
        action: 'Provide expected/tentative inauguration date',
      },
    ],
  },
  {
    id: 'target-completion',
    group: 'Overall Project',
    shortLabel: '7. Target Completion Date',
    title: '7. Projects - Missing or Expired Target Completion Date (all active, non-completed projects)',
    severity: 'critical',
    count: 74,
    description: 'Overall target completion missing, expired, or revised date also expired.',
    columns: [
      { field: 'slNo', headerName: 'Sl. No.', width: 80 },
      { field: 'organisation', headerName: 'Port/Organisation', minWidth: 180, flex: 1.2 },
      { field: 'projectCode', headerName: 'Project ID/Code', width: 110 },
      { field: 'projectName', headerName: 'Project Name', minWidth: 220, flex: 1.6 },
      { field: 'stage', headerName: 'Project Stage/Status', width: 160 },
      { field: 'milestones', headerName: 'Relevant Stage/Milestone', minWidth: 180, flex: 1.1 },
      { field: 'targetDate', headerName: 'Existing Target Date', width: 140 },
      { field: 'revisedDate', headerName: 'Revised Target Date', width: 140 },
      { field: 'issue', headerName: 'Current Status/Issue', minWidth: 220, flex: 1.5 },
      { field: 'action', headerName: 'Required Action/Update', minWidth: 200, flex: 1.3 },
    ],
    rows: [
      {
        slNo: 1,
        organisation: 'Jawaharlal Nehru Port Authority',
        projectCode: 'PR0006',
        projectName: 'Operationalization of Coastal Berth & Shallow Water Berth',
        stage: 'Under Implementation',
        milestones: 'Overall Project Target Completion Date',
        targetDate: '25-03-2026',
        revisedDate: 'Not Available',
        issue: 'Expired Target Completion Date; no revised date provided',
        action: 'Provide a revised target completion date with justification',
      },
      {
        slNo: 2,
        organisation: 'Mumbai Port Authority',
        projectCode: 'PR0051',
        projectName: 'Upgrading and modernisation of International Cruise Terminal',
        stage: 'Under Implementation',
        milestones: 'Overall Project Target Completion Date',
        targetDate: '11-09-2019',
        revisedDate: '30-06-2026',
        issue: 'Original target expired; revised date also requires fresh update',
        action: 'Urgent: provide a fresh revised target completion date',
      },
    ],
  },
  {
    id: 'project-category',
    group: 'Master Data',
    shortLabel: '8. Project Category',
    title: '8. Projects - Project Category Not Filled / Possibly Mismatched',
    severity: 'attention',
    count: 54,
    description: 'Master data: category blank or possibly mismatched with project scope.',
    columns: [
      { field: 'slNo', headerName: 'Sl. No.', width: 80 },
      { field: 'organisation', headerName: 'Port/Organisation', minWidth: 180, flex: 1.2 },
      { field: 'projectCode', headerName: 'Project ID/Code', width: 110 },
      { field: 'projectName', headerName: 'Project Name', minWidth: 220, flex: 1.6 },
      { field: 'stage', headerName: 'Project Stage/Status', width: 160 },
      { field: 'existingCategory', headerName: 'Existing Category', width: 140 },
      { field: 'suggestedCategory', headerName: 'Suggested Category', width: 140 },
      { field: 'issue', headerName: 'Current Status/Issue', minWidth: 200, flex: 1.4 },
      { field: 'action', headerName: 'Required Action/Update', minWidth: 200, flex: 1.3 },
    ],
    rows: [
      {
        slNo: 1,
        organisation: 'Mumbai Port Authority',
        projectCode: 'PR0020',
        projectName: 'Implementation of Port Enterprise Business Solution at First Floor',
        stage: 'Under Implementation',
        existingCategory: '-',
        suggestedCategory: '-',
        issue: 'Project Category field not filled',
        action: 'Assign an appropriate Project Category',
      },
      {
        slNo: 2,
        organisation: 'Jawaharlal Nehru Port Authority',
        projectCode: 'PR0007',
        projectName: 'Operationalization of JNP Hospital on PPP',
        stage: 'Under Implementation',
        existingCategory: 'Pontoon',
        suggestedCategory: 'Hospital',
        issue: "Name/scope suggests 'Hospital' but recorded category differs",
        action: 'Verify and correct Project Category if required',
      },
    ],
  },
];

export const SEVERITY_META = {
  critical: {
    label: 'Critical',
    badge: 'bg-rose-100 text-rose-800 dark:bg-rose-950/50 dark:text-rose-300',
    ring: 'ring-rose-200 dark:ring-rose-900/60',
    bar: 'bg-rose-500',
    soft: 'bg-rose-50/80 dark:bg-rose-950/20',
    icon: 'text-rose-600 dark:text-rose-400',
  },
  warning: {
    label: 'Needs data',
    badge: 'bg-amber-100 text-amber-900 dark:bg-amber-950/50 dark:text-amber-300',
    ring: 'ring-amber-200 dark:ring-amber-900/60',
    bar: 'bg-amber-500',
    soft: 'bg-amber-50/80 dark:bg-amber-950/20',
    icon: 'text-amber-600 dark:text-amber-400',
  },
  attention: {
    label: 'Attention',
    badge: 'bg-sky-100 text-sky-900 dark:bg-sky-950/50 dark:text-sky-300',
    ring: 'ring-sky-200 dark:ring-sky-900/60',
    bar: 'bg-sky-500',
    soft: 'bg-sky-50/80 dark:bg-sky-950/20',
    icon: 'text-sky-600 dark:text-sky-400',
  },
};

export function getDataQcSummary() {
  const totalIssues = DATA_QC_CHECKS.reduce((sum, c) => sum + c.count, 0);
  const bySeverity = DATA_QC_CHECKS.reduce(
    (acc, c) => {
      acc[c.severity] = (acc[c.severity] || 0) + c.count;
      return acc;
    },
    {}
  );
  const groups = [...new Set(DATA_QC_CHECKS.map((c) => c.group))];
  return { totalIssues, bySeverity, groups, checkCount: DATA_QC_CHECKS.length };
}

export function getDataQcCheckById(id) {
  return DATA_QC_CHECKS.find((c) => c.id === id) || null;
}
